### ISSUE TITLE
A2E SBt/reference pts figure alterations

### ISSUE THREAD

**Issue by Shawkshaw** [grinnellm/RebuildHG#14]
Can you please remove the green and yellow shading but keep the red?

![image](https://user-images.githubusercontent.com/6414082/107078373-1be11c80-67a3-11eb-8d78-f3ff0ed8cb0d.png)

can we add the box for the CHN productive period 75-85  similar to what we have in this figure? 

![image](https://user-images.githubusercontent.com/6414082/107078430-30bdb000-67a3-11eb-9d9c-967033f37ad3.png)

**Comment by grinnellm** [comment]
Not sure if you can see it, but there are two red shadings in the top figure: the red line and red shading around the line, and the red shading of the area below the red line. You want them both? Might be confusing.

**Comment by Shawkshaw** [comment]
You are right - please remove the red area shading but leave the shading for the variance on the LRP

**Comment by grinnellm** [comment]
Roger. Do you want to keep the grey shading around the solid black line?

**Comment by Shawkshaw** [comment]
Yes and can you add it to the other lines as well?  I wonder if there is over lap with other reference points?

**Comment by grinnellm** [comment]
There will be overlap. What colour do you want the dashed black line?

**Comment by grinnellm** [comment]
Black?

**Comment by grinnellm** [comment]
![image](https://user-images.githubusercontent.com/25674027/107087946-0ecb2a00-67b1-11eb-834d-00c651ea1c83.png)

**Comment by Shawkshaw** [comment]
Can you do a version without the variance on all the lines except keep it for the LRP?

**Comment by Shawkshaw** [comment]
Oh and can you please remove the catch?

**Comment by grinnellm** [comment]
If this looks good I'll make one without shading.
![image](https://user-images.githubusercontent.com/25674027/107089284-3ae7aa80-67b3-11eb-9fa1-e331599fbf15.png)

**Comment by Shawkshaw** [comment]
YEs this looks great thanks Matt - I am wondering about why the CV is so much larger for the 1.5SB0 and SB0 compared to the 0.3SB0

**Comment by grinnellm** [comment]
I think the CI inflates as the line increases along the y-axes. For example, the LRP (0.3SB_0) line is `lrp$median`, and the shaded area is between `lrp$lower` and `lrp$upper`. For the 1.5 SB_0 line, the line is `lrp$median / 0.3 * 1.5`, and the shaded area is between `lrp$lower / 0.3 * 1.5` and `lrp$upper / 0.3 * 1.5`. Does that make sense? I could be doing this wrong though, so please check. You can see the code [here](https://github.com/pbs-assess/herringutils/blob/be6f954a7440f361a1cee1d0a0962db21f192e6a/R/figures.R#L902).

**Comment by Shawkshaw** [comment]
Yes I think the calculations in the code are correct and that is how we have done it for the LRP throughout- I am struggling with the idea that as the SB0 estimate is divided the accuracy of the estimate appears to get better? Nothing to change for now I will keep thinking about this :)

**Comment by grinnellm** [comment]
I think of the CI similar to a percentage (+/- 5%). As it goes up, so does the value, though the percentage stays the same and vice versa. But I could be wrong.

**Comment by grinnellm** [comment]
How's this looking?
![image](https://user-images.githubusercontent.com/25674027/107276875-83e46c80-6a08-11eb-8a1c-01e5eb19395e.png)

**Comment by Shawkshaw** [comment]
Matt can you please add the year to the x-axis?

**Comment by Shawkshaw** [comment]
Can you also please add another reference pt line (dashed another shade of green maybe) at 1.125xB0? 
For both versions - with and without CIs :)

Have you pushed the code for these plots?

**Comment by grinnellm** [comment]
Yes they're pushed (herringutils). I just saw this and I will work on it now.

**Comment by grinnellm** [comment]
What do you think of this? I made the upper line "darkgreen" which was perhaps a mistake, since it looks black.
![image](https://user-images.githubusercontent.com/25674027/107563912-807eeb80-6b96-11eb-9b5e-d98d52cc43e8.png)

**Comment by Shawkshaw** [comment]
Great for now - we will see if anyone has edits later :)

**Comment by Shawkshaw** [comment]
Can have a version with CVs?  I know it will be messy but it will be asked for

**Comment by grinnellm** [comment]
![image](https://user-images.githubusercontent.com/25674027/107571324-9e9d1980-6b9f-11eb-8da9-f12a41f48103.png)

**Comment by Shawkshaw** [comment]
Ack not pretty - A few more alterations based on talking with Jaclyn 
- Can the top line 1.5Bo be switched back to the light green color from the 1st version
- Can the dashed black line be a yellow color
- Can the dashed light green line be changed to the dark green still dash 
- Keep CIs on all line except the dashed green

**Comment by grinnellm** [comment]
Like so?
![image](https://user-images.githubusercontent.com/25674027/107580968-44568580-6bac-11eb-8498-0bcd533cebb6.png)

**Comment by Shawkshaw** [comment]
hmm the yellow is hard to see, can we set it back to black

**Comment by grinnellm** [comment]
Orange?
![image](https://user-images.githubusercontent.com/25674027/107582298-28ec7a00-6bae-11eb-9ccb-905cccf04a24.png)

**Comment by Shawkshaw** [comment]
Yes - Orange is much better thanks! Can we keep it dashed too

**Comment by grinnellm** [comment]
Final final? :)
![image](https://user-images.githubusercontent.com/25674027/107583181-69002c80-6baf-11eb-951b-7f72cc0eaa7d.png)

**Comment by Shawkshaw** [comment]
Can you make the dashed green line darker or black?  and then add the CIs to all the line except that one?

**Comment by grinnellm** [comment]
![image](https://user-images.githubusercontent.com/25674027/107583830-5c300880-6bb0-11eb-9563-22bceed206b6.png)

**Comment by grinnellm** [comment]
![image](https://user-images.githubusercontent.com/25674027/107584721-d57c2b00-6bb1-11eb-96fa-7ca167b2524c.png)

**Comment by Shawkshaw** [comment]
Awesome thanks! We are going to send to FM and see what they think

**Comment by grinnellm** [comment]
I'm going to be over-optimistic and close this. Open it if you need..
