### ISSUE TITLE
A2W spawn index time series figure edits

### ISSUE THREAD

**Issue by Shawkshaw** [grinnellm/RebuildHG#15]
![2WSpawnIndexPercent](https://user-images.githubusercontent.com/6414082/110867348-67dc2100-827b-11eb-92b4-7114cefad0e4.png)

-panel a: Can we make the second horizontal line (0.5*aveB_82-92) dashed?
-panel b: Can we change color of bars to black and grey to differentiate from the section colors?

**Comment by grinnellm** [comment]
Let me know what you think:
![SpawnIndexChange](https://user-images.githubusercontent.com/25674027/111006395-93294380-8341-11eb-9fd9-c7a464c63d41.png)

**Comment by grinnellm** [comment]
Top panel looks a bit squished?

**Comment by Shawkshaw** [comment]
Looks good thanks Matt!
