### ISSUE TITLE
Temporal distribution of spawn

### ISSUE THREAD

**Issue by grinnellm** [grinnellm/RebuildHG#7]
a.	Start date by location  (Separate plot for end date by location as well?)
b.	Start with an across coast comparisons by SAR and then zoom in on the HG by substocks

**Comment by Shawkshaw** [comment]
I think this one is the SpawnTiming.png plot.  
Could we do this for the HG aggregate and the other aggregate SARs?

**Comment by grinnellm** [comment]
Yes we can! Set line 67 (`spUnitName <- "Region"`) . To see other areas, set line 64 (`region <-`) -- you will have to run `Summary.R` first though, in the DataSummaries repo.
