### ISSUE TITLE
Annual length of each spawn (similar to #7)

### ISSUE THREAD

**Issue by grinnellm** [grinnellm/RebuildHG#9]
a.	Plot annual number of days of spawning by year (end date - start date)
b.	Plots for aggregates (2E/2W) and each substock (Sections 006, 021/025, 023/024, 002, 003)

**Comment by Shawkshaw** [comment]
I think this is the SpawnDuration.png plots for the mean duration of spawn.
How much variation in duration of spawn is there within a year?  I am curious if there are longer spawn events and shorter events in a single year?

Can we also do the mean duration plots for HG aggregate and the other SARs? :)

**Comment by grinnellm** [comment]
Check my recent commit -- I added error bars for standard deviation. It's pretty ugly. Maybe it would be better to show boxplots for each year. Or just the raw points? What do you think?
